import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from '../context/ThemeProvider';
import { SidebarAndSearchbarComponent } from '@/components/sidebar-and-searchbar';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Tokeet Help Center",
  description: "Generated by Tokeet",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the entire application with ThemeProvider */}
        <ThemeProvider>
          {/* Wrap all children with SidebarAndSearchbarComponent */}
          <SidebarAndSearchbarComponent>
          <main className="flex-1 overflow-y-auto">{children}</main>
          </SidebarAndSearchbarComponent>
        </ThemeProvider>
      </body>
    </html>
  );
}
